# This configuration file contains the custom configurations parameters
# for the CI workflow to run with the example data.

builds_to_run: ["genome"]

resolutions_to_run: ["all-time"]

subtypes: ["a"]
